### ISSUE TITLE
QUIZ 1

### ISSUE THREAD

**Issue by azmanyasin** [STIA1113-A201-GROUP-H/QUIZZES#1]
### **INSTRUCTOR**
Write a program to compute the ideal weight for both males and females. According to one study, the ideal weight for a female is 40 kg plus 5 kg for each inch in height over 5 feet. For example, the ideal weight for a female who is 5'3" would be 40 + 15 = 55 kg. 

For a male, the ideal weight is 50 kg plus 6 kg for each inch in height over 5 feet. For example, the ideal weight for a male who is 6'2" would be 50 + 14*6 = 134kg. 

Your program should ask the user to enter his/her height in feet and inches (both as integers—so a person 5'3" would enter the 5 and the 3). It should then compute and print both the ideal weight for a female and the ideal weight for a male. The general outline of your main function would be as follows:

1.	Declare your variables (think about what variables you need—you need to input two pieces of information (what?), then you need some variables for your calculations (see the following steps)
2.	Get the input (height in feet and inches) from the user
3.	Compute the total number of inches of height (convert feet and inches to total inches)
4.	Compute the ideal weight for a female and the ideal weight for a male (here you basically convert the "word" description above to assignment statements)
5.	Print the answers 
6.	Plan your program, then type it in, compile, and run it. Be sure it gives correct answers.

### **SUBMISSION**
1. Coding
2. Input
3. Output

**Comment by ChunWai279321** [comment]
https://github.com/ChunWai279321/QUIZ

**Comment by ChunWai279321** [comment]
https://github.com/ChunWai279321/QUIZ

**Comment by ChunWai279321** [comment]
https://github.com/ChunWai279321/QUIZ/blob/master/Quiz1/src/Q1.java

**Comment by SNaqilah** [comment]
https://github.com/SNaqilah/Quiz.git

**Comment by YongBoonKeat** [comment]
https://github.com/YongBoonKeat/Quiz

**Comment by Esyaa00** [comment]
https://github.com/Esyaa00/Quiz1.git

**Comment by ngchunlong279645** [comment]
https://github.com/ngchunlong279645/quiz1/tree/master/QUIZ1/src

**Comment by nurqurratuaini** [comment]
https://github.com/nurqurratuaini/exercises/tree/main/Quiz1

**Comment by Ainurnatasya17** [comment]
https://github.com/Ainurnatasya17/Quiz1.git

**Comment by ChongCheeTwau278751** [comment]
https://github.com/ChongCheeTwau278751/Quiz-1

**Comment by kellyloh811** [comment]
https://github.com/kellyloh811/ProgrammingQuiz/tree/master/Quiz/src

**Comment by piqahamir** [comment]
https://github.com/piqahamir/Quiz.git

**Comment by lohsiewchin** [comment]
Loh Siew Chin 278723
https://github.com/kellyloh811/ProgrammingQuiz/tree/master/Quiz/src

**Comment by athirahbazilah** [comment]
https://github.com/athirahbazilah/Quiz.git

**Comment by tehyeexin** [comment]
TEH YEE XIN 278070
https://github.com/tehyeexin/QUIZ-1---STIA1113.git

**Comment by NGZIHENG** [comment]
https://github.com/NGZIHENG/NgZiHeng278024quiz.git

**Comment by jiakee1026** [comment]
https://github.com/jiakee1026/Quiz1

**Comment by MohamadAmmar123** [comment]
https://github.com/MohamadAmmar123/STIA1113/tree/master/STIA1113/src/Quiz1

**Comment by LimKitEeNatelie** [comment]
https://github.com/LimKitEeNatelie/Quiz1.git

**Comment by Nurafiza058** [comment]
https://github.com/Nurafiza058/ExcerciseProg1/tree/main/quiz

**Comment by MohamadAmmar123** [comment]
https://github.com/MohamadAmmar123/STIA1113/tree/master/STIA1113/src/Quiz1

**Comment by khooyenni** [comment]
KHOO YEN NI 278520
https://github.com/khooyenni/Quiz1.git

**Comment by JasonLau278177** [comment]
https://github.com/JasonLau278177/Quiz1-.git

**Comment by chunkhai8** [comment]
https://github.com/chunkhai8/quiz

**Comment by zhiyi16510** [comment]
https://github.com/zhiyi16510/Quiz1-Ideal-Weight-.git

**Comment by wanizzat836** [comment]
https://github.com/wanizzat836/Quiz1.git

**Comment by qingyunleong** [comment]
https://github.com/qingyunleong/Quiz

**Comment by WoonZhunPing** [comment]
https://github.com/WoonZhunPing/Quiz1

**Comment by ChunWai279321** [comment]
https://github.com/ChunWai279321/QUIZZES/tree/master/Quiz/src

**Comment by ffangtn** [comment]
https://github.com/ffangtn/Quiz1/tree/master/quiz/src

**Comment by Dayat102** [comment]
https://github.com/Dayat102/Quiz2.git
![Annotation 2020-11-06 095506](https://user-images.githubusercontent.com/73527232/98319598-10534d80-201c-11eb-91af-2a2b593a93f9.png)

**Comment by Chong-LeeTing** [comment]
https://github.com/Chong-LeeTing/Quiz1.git

**Comment by puteriwan** [comment]
https://github.com/puteriwan/Quiz/tree/master/Quiz/src

**Comment by FatinShamas** [comment]
https://github.com/FatinShamas/QUIZ.git

**Comment by Farahanim-nym** [comment]
https://github.com/Farahanim-nym/quiz1

**Comment by izannuddin** [comment]
https://github.com/izannuddin/quiz1/commit/6a89ce178a08120e0a2c3aa6b5c9d9503ea7b2d2#diff-8a8f4eb346fd662bf60d7cbf685ba5f23fd1f0e36cbc0f8563579cf6ac190f00

**Comment by izannuddin** [comment]
https://github.com/izannuddin/quiz1/tree/master/quiz1/src/quiz1

**Comment by shakir277980** [comment]
https://github.com/shakir277980/quiz1.git

**Comment by Pee278802** [comment]
https://github.com/Pee278802/quiz1/tree/master/QUIZ

**Comment by leetzongying** [comment]
https://github.com/leetzongying/Quiz1
